[package]
name = "line-stitch"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies]
smallvec = "0.6.0"
fnv="1.0.6"
itertools="0.7.4"
euclid="0.16.*"

[dependencies.aabb-quadtree]
path = "../aabb-quadtree"

[dev-dependencies]
permutohedron="0.2.4"
